using Content.Client.Parallax.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

using Content.Client._Orbitra.UserInterface; // Orbitra-Edit

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    [Dependency] private IRobustRandom _random = default!;

    public const string StyleIdentifierMainMenu = "mainMenu";
    public const string StyleIdentifierMainMenuVBox = "mainMenuVBox";

    private static readonly ProtoId<ParallaxPrototype>[] Parallaxes =
    [
        "Wizard",
        "TrainStation",
        "PlasmaStation",
        "AmberStation",
        "FastSpace",
        "AspidParallax",
        "OriginStation",
        "Default",
        "Sky",
        "KettleStation",
        "BagelStation",
        "ExoStation",
        "SnowballStation"
    ];

    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        Content.Client._Orbitra.UserInterface.OrbitraEditorStyles.Apply(this); // Orbitra-Edit

        // I don't just enumerate them all as there's some hideous parallaxes, and it's easier
        // to update an allowlist than to randomly get an ugly one to fix a blocklist.
        BackgroundParallax.ParallaxPrototype = _random.Pick(Parallaxes).Id;

        // Orbitra-Edit - бренд выводится текстом в XAML.

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;
    }
}
