using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Windows;

[GenerateTypedNameReferences]
public sealed partial class ActionsWindow : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
{
    public const string StyleClassActionSearchBox = "actionSearchBox";

    public MultiselectOptionButton<Filters> FilterButton { get; private set; }

    /// <summary>
    /// Whether the displayed actions or search filter needs updating.
    /// </summary>
    public bool UpdateNeeded;

    public ActionsWindow()
    {
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit

        SearchContainer.AddChild(FilterButton = new Content.Client._Orbitra.UserInterface.OrbitraMultiselectButton<Filters> // Orbitra-Edit
        {
            Label = Loc.GetString("ui-actionmenu-filter-button")
        });

        foreach (var filter in Enum.GetValues<Filters>())
        {
            FilterButton.AddItem(Loc.GetString($"ui-actionmenu-{filter.ToString().ToLower()}"), filter);
        }
    }

    public enum Filters
    {
        Enabled,
        Item,
        Innate,
        Instant,
        Targeted
    }
}
