- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: _Lime/Imported/Monolith/Clothing/OuterClothing/Armor/bulletproof.rsi # Lime-Edit - текстуры Monolith с сохранением лицензии
    state: icon
  product: CrateSecurityArmor
  cost: 1750
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: _Lime/Imported/DeadSpace/Objects/Weapons/Guns/Battery/disabler.rsi # Lime-Edit - текстуры DeadSpace с сохранением лицензии
    state: base
  product: CrateSecurityNonlethal
  cost: 4000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: _Lime/Imported/Monolith/Objects/Misc/handcuffs.rsi # Lime-Edit - текстуры Monolith с сохранением лицензии
    state: handcuff
  product: CrateRestraints
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: _Lime/Imported/DeadSpace/Clothing/Head/Hoods/Bio/security.rsi # Lime-Edit - текстуры DeadSpace с сохранением лицензии
    state: icon
  product: CrateSecurityBiosuit
  cost: 1600
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: _Lime/Imported/DeadSpace/Objects/Specific/Security/barrier.rsi # Lime-Edit - текстуры DeadSpace с сохранением лицензии
    state: idle
  product: DeployableBarrier
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonlethalThrowables
  icon:
    sprite: _Lime/Imported/Forge/Forge/Objects/Weapons/Grenades/stingergrenade.rsi # Lime-Edit - текстуры Forge с сохранением лицензии
    state: icon
  product: CrateSecNonlethalThrowables
  cost: 2500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: _Lime/Imported/DeadSpace/Structures/Storage/closet.rsi # Lime-Edit - текстуры DeadSpace с сохранением лицензии
    state: genpop
  product: LockerPrisoner
  cost: 300
  category: cargoproduct-category-name-security
  group: market
