using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Inventory.Windows;

[GenerateTypedNameReferences]
public sealed partial class StrippingWindow : UserInterface.Controls.FancyWindow
{
    public StrippingWindow()
    {
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit - та же оболочка для второго варианта инвентаря.
        LayoutContainer.SetAnchorAndMarginPreset(this, LayoutContainer.LayoutPreset.Center);
    }
}
