using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class EscapeMenu : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
{
    public EscapeMenu()
    {
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.Lobby.OrbitraEntryWindow.Attach(this); // Orbitra-Edit

        // TODO: removed with https://github.com/space-wizards/space-station-14/pull/44431
        var uriOpener = IoCManager.Resolve<IUriOpener>();
        var cfg = IoCManager.Resolve<IConfigurationManager>();

        var bugReport = cfg.GetCVar(CCVars.InfoLinksBugReport);
        if (!string.IsNullOrWhiteSpace(bugReport))
        {
            BugReportButton.OnPressed += _ => uriOpener.OpenUri(bugReport);
        }
        else
        {
            BugReportButton.Visible = false;
        }
    }
}
