using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

using Content.Client._Orbitra.UserInterface; // Orbitra-Edit

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
    {
        [Dependency] private IClientAdminManager _adminManager = default!;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit
            IoCManager.InjectDependencies(this);

            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-misc"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(2, Loc.GetString("ui-options-tab-controls"));
            Tabs.SetTabTitle(3, Loc.GetString("ui-options-tab-audio"));
            Tabs.SetTabTitle(4, Loc.GetString("ui-options-tab-accessibility"));
            Tabs.SetTabTitle(5, Loc.GetString("ui-options-tab-admin"));

            UpdateTabs();
            Content.Client._Orbitra.UserInterface.OrbitraOptionButton.BindSelection(OrbitraTabSelect, args => Tabs.CurrentTab = args.Id); // Orbitra-Edit
            Tabs.OnTabChanged += index => OrbitraTabSelect.SelectId(index); // Orbitra-Edit: синхронизация при открытии вкладки командой.
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            Tabs.SetTabVisible(5, isAdmin);
            // Orbitra added start - все разделы доступны без переполнения заголовков.
            OrbitraTabSelect.Clear();
            for (var i = 0; i < Tabs.ChildCount; i++)
                if (Tabs.GetTabVisible(i))
                    OrbitraTabSelect.AddItem(Tabs.GetActualTabTitle(i), i);
            if (Tabs.CurrentTab == 5 && !isAdmin)
                Tabs.CurrentTab = 0;
            OrbitraTabSelect.SelectId(Tabs.CurrentTab);
            // Orbitra added end

            GraphicsTab.Control.ReloadValues();
            MiscTab.Control.ReloadValues();
            AccessibilityTab.Control.ReloadValues();
            AudioTab.Control.ReloadValues();
            AdminOptionsTab.Control.ReloadValues();
        }
    }
}
