using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogsWindow : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
{
    public AdminLogsWindow()
    {
        RobustXamlLoader.Load(this);
        AddStyleClass("OrbitraPreserveHorizontalScroll"); // Orbitra-Edit
        Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit
    }
}
