<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>../../../bin/Orbitra.DevHost/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Content.Tests" />
    <!-- Orbitra added start - backend должен быть доступен default ALC до загрузки sandboxed client. -->
    <ProjectReference Include="../VoiceChatBackend/Orbitra.VoiceChatBackend.csproj" />
    <!-- Orbitra added end -->
  </ItemGroup>
</Project>
