using Content.Client.CrewManifest.UI;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

using Content.Client._Orbitra.UserInterface; // Orbitra-Edit

namespace Content.Client.CrewManifest;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestUi : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
{
    public CrewManifestUi()
    {
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit

        StationName.AddStyleClass("LabelBig");
    }

    public void Populate(string name, CrewManifestEntries? entries)
    {
        CrewManifestListing.RemoveAllChildren();

        StationNameContainer.Visible = entries != null;
        StationName.Text = name;

        if (entries == null)
            return;

        CrewManifestListing.AddCrewManifestEntries(entries);
    }
}
