using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        UnsubscribeOrbitraModel(); // Orbitra-Edit: симметричная смена модели.
        _markingsModel = model;
        SubscribeOrbitraModel(); // Orbitra-Edit
        UpdateMarkings(); // Orbitra-Edit: модель может быть заполнена до подключения.
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        SubscribeOrbitraModel(); // Orbitra-Edit
        UpdateMarkings(); // Orbitra-Edit: обновления вне дерева не теряются.
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        UnsubscribeOrbitraModel(); // Orbitra-Edit
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganTabs.RemoveAllChildren();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            var control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group);
            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = i > 1;
    }
}
