using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private IPrototypeManager _protomanager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private ISharedPlayerManager _playerManager = default!;

        private readonly Button _createNewCharacterButton;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;
        public event Action? CreateCharacter; // Orbitra-Edit - проверка несохранённых изменений перед созданием.

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // Orbitra-Edit - фон задаётся локальным стилем редактора.

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                CreateCharacter?.Invoke(); // Orbitra-Edit
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            InitializeOrbitraSetup(profileEditor); // Orbitra-Edit
            RulesButton.OnPressed += _ => Content.Client._Orbitra.Lobby.OrbitraEditorStyles.OpenWindow(new RulesAndInfoWindow()); // Orbitra-Edit

            StatsButton.OnPressed += _ => Content.Client._Orbitra.Lobby.OrbitraEditorStyles.OpenWindow(new PlaytimeStatsWindow()); // Orbitra-Edit

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
            _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, _ => ReloadCharacterPickers());
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.RemoveAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            var maxCharactersSlots = _cfg.GetCVar(CCVars.GameMaxCharacterSlots);

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", maxCharactersSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_protomanager,
                    _playerManager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                if (slot >= maxCharactersSlots)
                {
                    characterPickerButton.SetOnlyStyleClass(ContainerButton.StylePseudoClassDisabled);
                    characterPickerButton.ToolTip =
                        Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                                      ("maxCharacters", maxCharactersSlots));
                }

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= maxCharactersSlots;
            Characters.AddChild(_createNewCharacterButton);
            RefreshOrbitraCharacterTitle(); // Orbitra-Edit
        }
    }
}
