using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            Content.Client._Orbitra.UserInterface.OrbitraMenuBackground.Attach(this, Background, LobbyBackground); // Orbitra-Edit
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(LobbyFrame, LayoutPreset.Wide); // Orbitra-Edit - авторство вне центральной области.
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            InitializeOrbitraLayout(); // Orbitra-Edit - компоновка и боковые панели.
        }

        public void SwitchState(LobbyGuiState state)
        {
            SwitchOrbitraState(state); // Orbitra-Edit - редактор использует всю область, без второго превью.
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
