using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

using Content.Client._Orbitra.UserInterface; // Orbitra-Edit

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : Content.Client.UserInterface.Controls.FancyWindow // Orbitra-Edit
{
    [Dependency] private ISharedAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    public ObserveWarningWindow()
    {
        Title = Loc.GetString("observe-warning-window-title");
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.Attach(this); // Orbitra-Edit
        IoCManager.InjectDependencies(this);
        var player = _playerManager.LocalSession;

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveButton.Text = Loc.GetString("observe-as-player");
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }

        ObserveButton.OnPressed += _ => { this.Close(); };
        NevermindButton.OnPressed += _ => Content.Client._Orbitra.UserInterface.OrbitraEntryWindow.RequestClose(this); // Orbitra-Edit
    }
}
