using System;
using Content.Shared._Orbitra.VoiceChat;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Timing;

namespace Content.Client._Orbitra.VoiceChat;

/// <summary>
/// Records a short local microphone sample and plays it back without sending it to the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OrbitraMicrophoneTestControl : BoxContainer
{
    private const int DurationSeconds = 3;
    [Dependency] private IAudioManager _audio = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private ILogManager _log = default!;
    private readonly short[] _frame = new short[OrbitraVoiceChatPolicy.SamplesPerFrame];
    private readonly short[] _recording = new short[OrbitraVoiceChatPolicy.SampleRate * DurationSeconds];
    private OrbitraVoiceChatCapture? _capture;
    private AudioStream? _stream;
    private IAudioSource? _source;
    private TimeSpan _deadline;
    private string _device = string.Empty;
    private int _sampleCount;
    public Func<string> GetDeviceName { get; set; } = () => string.Empty;

    public OrbitraMicrophoneTestControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TestButton.OnPressed += _ => ToggleTest();
    }

    private void ToggleTest()
    {
        if (_capture != null || _source != null)
        {
            StopTest();
            return;
        }

        try
        {
            _device = GetDeviceName();
            _capture = new OrbitraVoiceChatCapture();
            if (!_capture.Start(_device))
            {
                FailTest();
                return;
            }

            _deadline = _timing.RealTime + TimeSpan.FromSeconds(DurationSeconds + 2);
            TestButton.Text = Loc.GetString("orbitra-voice-test-stop");
            StatusLabel.Text = Loc.GetString("orbitra-voice-test-recording");
        }
        catch (Exception e)
        {
            _log.GetSawmill("orbitra.voice").Warning("Microphone test failed: {0}", e);
            FailTest();
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_capture == null && _source == null)
            return;

        try
        {
            if (!string.Equals(_device, GetDeviceName(), StringComparison.Ordinal))
            {
                StopTest();
                return;
            }

            if (_capture != null)
            {
                if (!_capture.IsCapturing || _timing.RealTime >= _deadline)
                {
                    FailTest();
                    return;
                }

                // Ограничиваем работу за кадр, не записывая больше трёх секунд.
                for (var i = 0; i < 10 && _sampleCount < _recording.Length && _capture.TryReadFrame(_frame); i++)
                {
                    Array.Copy(_frame, 0, _recording, _sampleCount, _frame.Length);
                    _sampleCount += _frame.Length;
                    var peak = 0;
                    foreach (var sample in _frame)
                        peak = Math.Max(peak, Math.Abs((int) sample));
                    InputLevel.Value = peak / 32768f;
                }

                if (_sampleCount == _recording.Length)
                    PlayRecording();
            }
            else if (_source != null && (!_source.Playing || _timing.RealTime >= _deadline))
            {
                StopTest();
                StatusLabel.Text = Loc.GetString("orbitra-voice-test-done");
            }
        }
        catch (Exception e)
        {
            _log.GetSawmill("orbitra.voice").Warning("Microphone test failed: {0}", e);
            FailTest();
        }
    }

    private void PlayRecording()
    {
        _capture?.Dispose();
        _capture = null;
        _stream = _audio.LoadAudioRaw(_recording, 1, OrbitraVoiceChatPolicy.SampleRate, "Microphone test");
        _source = _audio.CreateAudioSource(_stream);
        if (_source == null)
        {
            FailTest();
            return;
        }

        _source.Global = true;
        _source.Gain = 1f;
        _source.StartPlaying();
        _deadline = _timing.RealTime + TimeSpan.FromSeconds(DurationSeconds + 1);
        InputLevel.Value = 0;
        StatusLabel.Text = Loc.GetString("orbitra-voice-test-playing");
    }

    private void FailTest()
    {
        StopTest();
        StatusLabel.Text = Loc.GetString("orbitra-voice-test-error");
    }

    private void StopTest()
    {
        _capture?.Dispose();
        _capture = null;
        // При смене устройства движок уже мог освободить источник.
        try
        {
            _source?.StopPlaying();
            _source?.Dispose();
        }
        catch (Exception) { }
        _source = null;
        _stream?.Dispose();
        _stream = null;
        Array.Clear(_recording);
        _sampleCount = 0;
        InputLevel.Value = 0;
        TestButton.Text = Loc.GetString("orbitra-voice-test-start");
        StatusLabel.Text = Loc.GetString("orbitra-voice-test-hint");
    }

    protected override void VisibilityChanged(bool newVisible)
    {
        base.VisibilityChanged(newVisible);
        if (!newVisible)
            StopTest();
    }

    protected override void ExitedTree()
    {
        StopTest();
        base.ExitedTree();
    }
}
