- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtBartender
  name: bartender's uniform
  description: A nice and tidy uniform. Shame about the bar though.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/bartender.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/bartender.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtChaplain
  name: chaplain's jumpskirt
  description: It's a black jumpskirt, often worn by religious folk.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/chaplain.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/chaplain.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtChef
  name: chef uniform
  description: Can't cook without this.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/chef.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/chef.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtHydroponics
  name: hydroponics jumpskirt
  description: Has a strong earthy smell to it. Hopefully it's merely dirty as opposed to soiled.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/hydro.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/hydro.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtJanitor
  name: janitor jumpskirt
  description: The jumpskirt for the poor sop with a mop.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janitor.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janitor.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtMime
  name: mime jumpskirt
  description: ...
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/mime.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/mime.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLibrarian
  name: librarian jumpskirt
  description: A cosy green jumper fit for a curator of books.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/librarian.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/librarian.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtCurator
  name: sensible skirt
  description: It's sensible. Too sensible...
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/curator.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/curator.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtPerformer
  name: performer's jumpskirt
  description: Hi, I'm Scott, president of Donk Pizza. Have you heard of [FAMOUS VIRTUAL PERFORMER]?
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpskirts/Service/performer.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpskirts/Service/performer.rsi

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtJanimaid
  name: janitorial maid uniform
  description: For professionals, not the posers.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janimaid.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janimaid.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtJanimaidmini
  name: janitorial maid uniform with miniskirt
  description: Elite service, not some candy wrappers.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janimaidmini.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/janimaidmini.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtMusician
  name: musician's skirt
  description: A fancy skirt for the musically inclined. Perfect for any lounge act!
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/musician.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/musician.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtPsychologist
  name: psychologist suitskirt
  description: I don't lose things. I place things in locations which later elude me.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/psychologist.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/psychologist.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtClown
  name: clown skirt
  description: HONK!
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/clown.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/clown.rsi # Lime-Edit - графика Monolith
  - type: Tag
    tags:
    - ClownSuit
    - WhitelistChameleon

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLawyerRed
  name: red lawyer suitskirt
  description: A flashy red suitskirt worn by lawyers and show-offs.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerred.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerred.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLawyerBlue
  name: blue lawyer suitskirt
  description: A flashy blue suitskirt worn by lawyers and show-offs.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerblue.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerblue.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLawyerBlack
  name: black lawyer suitskirt
  description: A subtle black suitskirt worn by lawyers and gangsters.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerblack.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerblack.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLawyerPurple
  name: purple lawyer suitskirt
  description: A stylish purple piece worn by lawyers and show people.
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerpurple.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyerpurple.rsi # Lime-Edit - графика Monolith

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtLawyerGood
  name: good lawyer's suitskirt
  description: A tacky suitskirt perfect for a CRIMINAL lawyer!
  components:
  - type: Sprite
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyergood.rsi # Lime-Edit - графика Monolith
  - type: Clothing
    sprite: _Lime/Imported/Monolith/Clothing/Uniforms/Jumpskirt/lawyergood.rsi # Lime-Edit - графика Monolith
