using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;

namespace Content.Client.Changelog;

[GenerateTypedNameReferences]
public sealed partial class ChangelogWindow : FancyWindow
{
    [Dependency] private IClientAdminManager _adminManager = default!;
    [Dependency] private ChangelogManager _changelog = default!;

    public ChangelogWindow()
    {
        RobustXamlLoader.Load(this);
        Content.Client._Orbitra.Lobby.OrbitraEntryWindow.Attach(this); // Orbitra-Edit
        InitializeOrbitraJournal(); // Orbitra-Edit: представление и загрузка вынесены в модуль форка.
    }

    protected override void Opened()
    {
        base.Opened();
        _changelog.SaveNewReadId();
        LoadOrbitraJournal(); // Orbitra-Edit
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _adminManager.AdminStatusUpdated += RefreshOrbitraSections; // Orbitra-Edit
    }

    protected override void ExitedTree()
    {
        _adminManager.AdminStatusUpdated -= RefreshOrbitraSections; // Orbitra-Edit
        CancelOrbitraJournalLoad(); // Orbitra-Edit
        base.ExitedTree();
    }
}

[UsedImplicitly, AnyCommand]
public sealed partial class ChangelogCommand : LocalizedCommands
{
    [Dependency] private IUserInterfaceManager _uiManager = default!;
    public override string Command => "changelog";

    public override void Execute(IConsoleShell shell, string argStr, string[] args)
    {
        _uiManager.GetUIController<ChangelogUIController>().OpenWindow();
    }
}
